### ISSUE TITLE
UX Design page - Swap jobs module URL for staging/production

### ISSUE THREAD

**Issue by mbifulco** [gymnasium/gymstatic#41]
This is to track work related to swapping out the jobs module on the UX design page.  On production, it'll need to have a different URL than staging, likely based on an environment variable on netlify.

Mike to work with Andrew on this.

**Comment by andrewpmiller** [comment]
Here's a (feature branch) placeholder UX landing page that _should_ select the appropriate Heroku URL based on the (final) build environment:
https://github.com/gymnasium/gymcms/blob/feature/uxjobmodule/hub-pages/ux-design.html

**Note:** You'll need to merge into staging and production branches to actually test the logic. By default Jekyll calls any build on Netlify a "production" build. The only way we can set `jekyll.environment` to "staging" is by explicitly building the staging branch. 🤖

**Comment by andrewpmiller** [comment]
Can we close this issue because #85 is a thing now...? Or do we only close it when it's 100% working? 🤓
