### ISSUE TITLE
404 Page Not Found for Take 5 Courses.

### ISSUE THREAD

**Issue by laurielim** [gymnasium/gymstatic#616]
Hi,

I was looking through your [Take 5 courses](https://www.thegymnasium.com/courses/take5) and then when I clicked on one of them, it took me to the wrong URL:
-  https://www.thegymnasium.com/courses/managing-your-time-like-a-pro instead of
-  https://www.thegymnasium.com/courses/take5/managing-your-time-like-a-pro

**Comment by andrewpmiller** [comment]
@laurielim - you are awesome! Thank you so much for reporting this to us — not to mention doing it here!

We've been doing some major refactoring and we missed this goof when we were testing. And, there is _always_ another bug. We'll fix this asap.
