### ISSUE TITLE
Responsive display glitch on UX landing page

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/gymstatic#96]
The "articles" card loses its height when the layout shrinks in width from 3-across to 2-across.

### 3-Across
![image](https://user-images.githubusercontent.com/5747506/59299324-658a0480-8c5a-11e9-9879-3ea45f9d54f8.png)

### 2-Across
![image](https://user-images.githubusercontent.com/5747506/59299392-83576980-8c5a-11e9-8a7c-ae778d57719a.png)

**Comment by jgagne** [comment]
Commit https://github.com/gymnasium/gymcms/commit/e44ae5db491663c8678d5e0759982a2dd1a68766 should produce the following layout:

## 3-Across
![ux-design-featured-3-col](https://user-images.githubusercontent.com/5142085/59310645-0ab1d680-8c75-11e9-85c5-f137076a80b3.png)

## 2-Across
![ux-design-featured-2-col](https://user-images.githubusercontent.com/5142085/59310662-1b624c80-8c75-11e9-9f77-7c16dc69b2f8.png)
